# Generated by Django 5.2.1 on 2025-06-04 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0004_alter_author_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='When the author is deleted is set False', verbose_name='Is Deleted'),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='profile',
            field=models.URLField(blank=True, null=True, verbose_name='Profile URL'),
        ),
        migrations.AlterField(
            model_name='author',
            name='rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Rating in AWS'),
        ),
    ]
