# Generated by Django 5.2.1 on 2025-06-04 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.CharField(blank=True, choices=[('Fiction', 'Fiction'), ('Non-Fiction', 'Non-Fiction'), ('Science Fiction', 'Science Fiction'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Biography', 'Biography')], max_length=100, null=True, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='amount_pages',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10000)], verbose_name='Amount of Pages'),
        ),
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
