# Generated by Django 5.2.1 on 2025-06-05 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0010_library_book_libraries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='library',
            options={'verbose_name_plural': 'Libraries'},
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20, verbose_name='Gender')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('age', models.PositiveIntegerField(editable=False, verbose_name='Age')),
                ('role', models.CharField(choices=[('A', 'Administrator'), ('R', 'Reader'), ('E', 'Employee')], max_length=30, verbose_name='Role')),
                ('active', models.BooleanField(default=True, verbose_name='Is_active')),
                ('libraries', models.ManyToManyField(related_name='members', to='library.library', verbose_name='Library')),
            ],
        ),
    ]
