# Generated by Django 5.2.1 on 2025-06-05 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0011_alter_category_options_alter_library_options_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='library.member', verbose_name='Publisher'),
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
