# Generated by Django 5.2.1 on 2025-06-05 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0012_alter_book_publisher_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique_for_date='date_of_created', verbose_name='Post Title')),
                ('text', models.TextField(verbose_name='Post Text')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Is Moderated')),
                ('date_of_created', models.DateField(verbose_name='Date of Created')),
                ('date_of_updated', models.DateField(auto_now=True, verbose_name='Date of Updated')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='library.member', verbose_name='Author')),
                ('library', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='library.library', verbose_name='Library')),
            ],
        ),
    ]
