# Generated by Django 5.2.1 on 2025-06-05 10:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0017_authordetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Event Title')),
                ('description', models.TextField(verbose_name='Event Description')),
                ('timestamp', models.DateField(verbose_name='Event Date')),
                ('books', models.ManyToManyField(related_name='events', to='library.book', verbose_name='Books')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='library.library', verbose_name='Library')),
            ],
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(default=django.utils.timezone.now, verbose_name='Registration Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='library.event', verbose_name='Event')),
                ('member', models.ManyToManyField(related_name='participants', to='library.member', verbose_name='Member')),
            ],
        ),
    ]
