# Generated by Django 5.2.1 on 2025-06-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0018_event_eventparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authordetail',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='authordetail',
            name='date_of_birth',
            field=models.DateField(null=True, verbose_name='Date of Birth'),
        ),
    ]
